# Практическое задание к уроку 2 "Матрицы и матричные операции"

# Часть 1

### Задание 1

___a.___
$$
A=
\begin{pmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}\\
a_{31} & a_{32}\\
a_{41} & a_{42}
\end{pmatrix}
,
B=
\begin{pmatrix}
b_{11} & b_{12}\\
b_{21} & b_{22}\\
b_{31} & b_{32}\\
b_{41} & b_{42}
\end{pmatrix}
$$

$AB$ - __неопределено__, т.к. число столбцов матрицы $A$ не соответствует числу строк матрицы $B$.

$BA$ - __неопределено__, т.к. число столбцов матрицы $B$ не соответствует числу строк матрицы $A$.


___б.___
$$
A=
\begin{pmatrix}
a_{11} & a_{12} & a_{13} & a_{14} & a_{15}\\
a_{21} & a_{22} & a_{23} & a_{24} & a_{25}
\end{pmatrix}
,
B=
\begin{pmatrix}
b_{11} & b_{12} & b_{13}\\
b_{21} & b_{22} & b_{23}\\
b_{31} & b_{32} & b_{33}\\
b_{41} & b_{42} & b_{43}\\
b_{51} & b_{52} & b_{53}
\end{pmatrix}
$$

$AB$ - __определено__, т.к. число столбцов матрицы $A$ соответствует числу строк матрицы $B$.
Размерность матрицы $AB$ - $2\times3$.

$BA$ - __неопределено__, т.к. число столбцов матрицы $B$ не соответствует числу строк матрицы $A$.


___в.___
$$
A=
\begin{pmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}\\
a_{41} & a_{42} & a_{43}\\
a_{51} & a_{52} & a_{53}\\
a_{61} & a_{62} & a_{63}\\
a_{71} & a_{72} & a_{73}\\
a_{81} & a_{82} & a_{83}
\end{pmatrix}
,
B=
\begin{pmatrix}
b_{11} & b_{12} & b_{13} & b_{14} & b_{15} & b_{16} & b_{17} & b_{18}\\
b_{21} & b_{22} & b_{23} & b_{24} & b_{25} & b_{26} & b_{27} & b_{28}\\
b_{31} & b_{32} & b_{33} & b_{34} & b_{35} & b_{36} & b_{37} & b_{38}
\end{pmatrix}
$$

$AB$ - __определено__, т.к. число столбцов матрицы $A$ соответствует числу строк матрицы $B$.
Размерность матрицы $AB$ - $8\times8$.

$BA$ - __определено__, т.к. число столбцов матрицы $B$ соответствует числу строк матрицы $A$.
Размерность матрицы $BA$ - $3\times3$.

_г._
$$
A=
\begin{pmatrix}
a_{11} & a_{12} & a_{13} & a_{14}\\
a_{21} & a_{22} & a_{23} & a_{24}\\
a_{31} & a_{32} & a_{33} & a_{34}\\
a_{41} & a_{42} & a_{43} & a_{44}
\end{pmatrix}
,
B=
\begin{pmatrix}
b_{11} & b_{12} & b_{13} & b_{14}\\
b_{21} & b_{22} & b_{23} & b_{24}\\
b_{31} & b_{32} & b_{33} & b_{34}\\
b_{41} & b_{42} & b_{43} & b_{44}
\end{pmatrix}
$$

$AB$ - __определено__, т.к. $A$ и $B$ квадратные матрицы одного размера.
Размерность матрицы $AB$ - $4\times4$.

$BA$ - __определено__, т.к. $B$ и $A$ квадратные матрицы одного размера.
Размерность матрицы $BA$  - $4\times4$.


### Задание 2

$$
A=
\begin{pmatrix}
1 & -2\\
3 & 0
\end{pmatrix}
,
B=
\begin{pmatrix}
4 & -1\\
0 & 5
\end{pmatrix}
$$

$$
A+B=
\begin{pmatrix}
1+4 & -2-1\\
3+0 & 0+5
\end{pmatrix}
=
\begin{pmatrix}
5 & -3\\
3 & 5
\end{pmatrix}
$$

$$
A\cdot B=
\begin{pmatrix}
(1\cdot4 + (-2)\cdot0) & (1\cdot(-1) + (-2)\cdot5)\\
(3\cdot4 + 0\cdot0) & (3\cdot(-1) + 0\cdot5)
\end{pmatrix}
=
\begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}
$$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Сумма матриц A и B равна: \n\n {A+B}\n')
print(f'Произведение матриц A и B равно: \n\n {np.dot(A,B)}')

Сумма матриц A и B равна: 

 [[ 5 -3]
 [ 3  5]]

Произведение матриц A и B равно: 

 [[  4 -11]
 [ 12  -3]]


### Задание 3

$$
A=
\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix}
,
B=
\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix}
,
C=
\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix}
$$

$$
3A-2B+4C=
3\cdot
\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix}
-
2\cdot
\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix}
+
4\cdot
\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
3\cdot1 & 3\cdot7\\
3\cdot3 & 3\cdot(-6)
\end{pmatrix}
-
\begin{pmatrix}
2\cdot0 & 2\cdot5\\
2\cdot2 & 2\cdot(-1)
\end{pmatrix}
+
\begin{pmatrix}
4\cdot2 & 4\cdot(-4)\\
4\cdot1 & 4\cdot1
\end{pmatrix}
=
\begin{pmatrix}
3 & 21\\
9 & -18
\end{pmatrix}
-
\begin{pmatrix}
0 & 10\\
4 & -2
\end{pmatrix}
+
\begin{pmatrix}
8 & -16\\
4 & 4
\end{pmatrix}
=
$$

$$
=
\begin{pmatrix}
3-0+8 & 21-10-16\\
9-4+4 & -18+2+4
\end{pmatrix}
=
\begin{pmatrix}
11 & -5\\
9 & -12
\end{pmatrix}
$$

In [3]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'3A-2B+4C=\n\n{np.dot(3,A)-np.dot(2,B)+np.dot(4,C)}')

3A-2B+4C=

[[ 11  -5]
 [  9 -12]]


### Задание 4

$$
A = 
\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end{pmatrix}
,
A^T =
\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}
$$

$$
A\cdot A^T=
\begin{pmatrix}
4\cdot4 + 1\cdot1 & 4\cdot5 + 1\cdot(-2) & 4\cdot2 + 1\cdot3\\
5\cdot4 + (-2)\cdot1 & 5\cdot5 + (-2)\cdot(-2) & 5\cdot2 + (-2)\cdot3\\
2\cdot4 + 3\cdot1 & 2\cdot5 + 3\cdot(-2) & 2\cdot2 + 3\cdot3
\end{pmatrix}
=
\begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}
$$

$$
A^T\cdot A=
\begin{pmatrix}
4\cdot4 + 5\cdot5 + 2\cdot2 & 4\cdot1 + 5\cdot(-2) + 2\cdot3\\
1\cdot4 + (-2)\cdot5 + 3\cdot2 & 1\cdot1 + (-2)\cdot(-2) + 3\cdot3
\end{pmatrix}
=
\begin{pmatrix}
45 & 0\\
0 & 14
\end{pmatrix}
$$

In [4]:
A = np.array([[4,1],[5,-2],[2,3]])
print(f'Произведение A и A\u1d40 равно: \n\n{np.dot(A,A.T)}\n')
print(f'Произведение A\u1d40 и A равно: \n\n{np.dot(A.T,A)}')

Произведение A и Aᵀ равно: 

[[17 18 11]
 [18 29  4]
 [11  4 13]]

Произведение Aᵀ и A равно: 

[[45  0]
 [ 0 14]]


### Задание 5

In [5]:
def matrix_product(matrix_a, matrix_b):
    '''Функция перемножения матриц matrix_a и matrix_b'''
    if len(matrix_a[0]) == len(matrix_b):
        result = [[0 for i in range(len(matrix_a))] \
                     for j in range(len(matrix_b[0]))]
        for i in range(len(matrix_a)):
            for j in range(len(matrix_b[0])):
                for x in range(len(matrix_a[0])):
                    result[i][j] += matrix_a[i][x] * matrix_b[x][j]
    else:
        result = "неопределено."
    return result

In [6]:
print(f'Произведение матриц \n\n\
{matrix_product([[1, 2, 3],[1, 3, 2]],[[1, 2],[2, 3],[3, 4]])}')

Произведение матриц 

[[14, 20], [13, 19]]


In [7]:
print(f'Произведение матриц \n\n\
{matrix_product([[1, 2, 3, 4],[1, 3, 2, 4]],[[1, 2],[2, 3],[3, 4]])}')

Произведение матриц 

неопределено.


# Часть 2

### Задание 1

___а.___
$$A=\begin{pmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{pmatrix};$$

$$detA=\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}
=
sinx \cdot sinx - cosx \cdot -cosx
=sin^2x+cos^2x
=1$$
___б.___
$$A=\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
Матрица $A$ является треугольной. Следовательно из 7-го свойства определителя матрицы её определитель равен произведению элементов, стоящих на главной диагонали.
$$detA=\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}
=4\cdot 5\cdot 9=180$$

In [8]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель матрицы A равен {np.linalg.det(A)}')

Определитель матрицы A равен 180.0


___в.___
$$A=\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix};$$

$$detA=\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}
=1\cdot 
\begin{vmatrix}
5 & 6\\
8 & 9
\end{vmatrix}
-2\cdot
\begin{vmatrix}
4 & 6\\
7 & 9
\end{vmatrix}
+3\cdot
\begin{vmatrix}
4 & 5\\
7 & 8
\end{vmatrix}
= (5\cdot9-8\cdot6)-2\cdot(4\cdot9-7\cdot6)+3\cdot(4\cdot8-7\cdot5)
=0$$

$$detA=\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}
=
(1\cdot 5\cdot 9 + 7\cdot 2\cdot 6 + 3\cdot 4\cdot 8) - (3\cdot 5\cdot 7 + 1\cdot 8\cdot 6 + 9\cdot 4\cdot 2)
=0$$

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель матрицы A равен  {np.linalg.det(A)}')

Определитель матрицы A равен  0.0


### Задание 2

___а.___

Так как для двух квадратных матриц одинакового размера справедливо правило $det(A\cdot B)=detA\cdot detB.$, то при $detA=4$ :

$$det(A^{2}) = det(A\cdot A)= detA \cdot detA = 4\cdot 4=14$$

___б.___

Согласно первому свойству определителей - определитель транспонированной матрицы равен определителю исходной.

Следовательно при $detA=4$ определитель $det(A^{T}) = det(A) = 4$

___в.___

Согласно правилу умножения матрицы на число:

$$
\lambda\cdot\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{m1} & a_{m2} & \cdots & a_{mn}\\ 
\end{pmatrix}=
\begin{pmatrix}
\lambda a_{11} & \lambda a_{12} & \cdots & \lambda a_{1n}\\ 
\lambda a_{21} & \lambda a_{22} & \cdots & \lambda a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
\lambda a_{m1} & \lambda a_{m2} & \cdots & \lambda a_{mn}\\ 
\end{pmatrix}
$$

Также согласно свойству определителя матрицы, умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число:

$$
\begin{vmatrix}
\lambda a_{11} & \lambda a_{12} & \cdots & \lambda a_{1n} \\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn}\\ 
\end{vmatrix}=
\lambda \cdot \begin{vmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn}\\ 
\end{vmatrix}
$$

Следовательно, в случае нахождения определителя матрицы, умноженной на число, множитель каждой строки матрицы может быть вынесен столько раз, сколько соответствует размерности матрицы:

$$
det(\lambda \cdot A)=
\begin{vmatrix}
\lambda a_{11} & \lambda a_{12} & \cdots & \lambda a_{1n} \\ 
\lambda a_{21} & \lambda a_{22} & \cdots & \lambda a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
\lambda a_{n1} & \lambda a_{n2} & \cdots & \lambda a_{nn}\\ 
\end{vmatrix}=
\lambda \cdot \begin{vmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
\lambda a_{21} & \lambda a_{22} & \cdots & \lambda a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
\lambda a_{n1} & \lambda a_{n2} & \cdots & \lambda a_{nn}\\ 
\end{vmatrix}
=
\lambda \cdot \lambda \cdot \begin{vmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
\lambda a_{n1} & \lambda a_{n2} & \cdots & \lambda a_{nn}\\ 
\end{vmatrix} = 
$$

$$
=\lambda ^n \cdot
\begin{vmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
\lambda a_{21} & \lambda a_{22} & \cdots & \lambda a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
\lambda a_{n1} & \lambda a_{n2} & \cdots & \lambda a_{nn}\\ 
\end{vmatrix}=
\lambda ^n \cdot det(A),
$$
где $n$ разрядность матрицы.

Следовательно при $det(A)=4$ выражение $det(2A)=det(A)\cdot 2^n=4\cdot 2^n$.


### Задание 3

$$A =
\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}
$$

Вычтя из второй строки исходной матрицы перыую строку умноженную на 2, получим матрицу в которой все элементы второй строки равны 0:

$$
detA =
\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}
=
\begin{vmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{vmatrix}
=0
$$

В случаях когда матрица имеет нулевую строку или нулевой столбец определитель матицы равен нулю. Следовательно матрица является __вырожденной__.

In [10]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
if np.linalg.det(A):
    print('Матрица A невырожденная.')
else:
    print('Матрица A вырожденная.')

Матрица A вырожденная.


### Задание 4

___а.___
$$A=\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$$

Третья строка матрицы A является суммой первых двух, следовательно может быть отброшена:

$$
A=\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}
=
\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}
$$

Поскольку есть минор 2-го порядка, отличный от нуля:

$$
\begin{pmatrix}
1 & 2\\ 
1 & 1
\end{pmatrix}
=1-2=-1
$$

Следовательно $r(A)=2$

In [11]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Ранг матрицы A равен: {np.linalg.matrix_rank(A)}')

Ранг матрицы A равен: 2


___б.___
$$A=\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$

Так как третий ряд является линейной комбинацией первого и второго рядов, его можно выбросить и провести ряд элементарных преобразований:

$$
\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}
=
\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}
=
\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & -1
\end{pmatrix}
$$

Полученная матрица имеет 4 минора 3-го порядка, два из которых отличны от нуля. Следовательно __ранг матрицы равен 3__.


$
\Delta =
\begin{vmatrix}
2 & 3 & 5 \\ 
0 & 0 & 2 \\ 
0 & 0 & 0 
\end{vmatrix} = 0;
$ 
$
\Delta =
\begin{vmatrix}
2 & 3 & 6\\ 
0 & 0 & 2\\ 
0 & 0 & -1
\end{vmatrix} = 0;
$
$
\Delta =
\begin{vmatrix}
2 & 5 & 6\\ 
0 & 2 & 2\\ 
0 & 0 & -1
\end{vmatrix} = -4;
$
$
\Delta =
\begin{vmatrix}
3 & 5 & 6\\ 
0 & 2 & 2\\ 
0 & 0 & -1
\end{vmatrix} = -6
$

In [12]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Ранг матрицы A равен: {np.linalg.matrix_rank(A)}')

Ранг матрицы A равен: 3
